# Generated by Django 5.2.11 on 2026-03-16 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nomenclature', '0003_nomenclature_fixed_weight_grams'),
        ('label_stations', '0007_alter_labelsstations_station_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('quantity_unit', models.CharField(choices=[('kg', 'Килограммы'), ('pcs', 'Штуки')], default='pcs', max_length=3, verbose_name='Единица измерения')),
                ('batch_number', models.CharField(max_length=100, verbose_name='Номер партии')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('sent', 'Отправлено'), ('completed', 'Выполнено'), ('error', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='Nomenclature.nomenclature', verbose_name='Номенклатура')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='label_stations.labelsstations', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Задание на печать',
                'verbose_name_plural': 'Задания на печать',
                'ordering': ['-created_at'],
            },
        ),
    ]
