# Generated by Django 5.2.11 on 2026-03-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printjob',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Номер партии'),
        ),
    ]
