# Generated by Django 5.2.11 on 2026-03-24 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_jobs', '0002_alter_printjob_batch_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='marking_date',
            field=models.DateField(default=datetime.date(2026, 3, 24), verbose_name='Дата маркировки'),
            preserve_default=False,
        ),
    ]
