# Generated by Django 5.2.15 on 2026-10-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_jobs', '0003_printjob_marking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Выполнено'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='last_error',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Ошибка отправки'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='printed_qty',
            field=models.FloatField(default=0, verbose_name='Напечатано'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='progress_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Прогресс получен'),
        ),
        migrations.AddField(
            model_name='printjob',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отправлено на станцию'),
        ),
    ]
