# Generated by Django 5.2.11 on 2026-02-04 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LabelTemplates', '0001_initial'),
        ('Packs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название атрибута')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Глобальный атрибут товара',
                'verbose_name_plural': 'Глобальные атрибуты товаров',
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название номенклатуры')),
                ('article', models.CharField(max_length=100, unique=True, verbose_name='Артикул')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='URL')),
                ('exp_date', models.IntegerField(verbose_name='Срок годности (суток)')),
                ('close_box_counter', models.IntegerField(verbose_name='Количество вложений в коробе')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные реквизиты')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок сортировки')),
                ('box_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomenclatures_box', to='Packs.pack', verbose_name='Тип упаковки (короб)')),
                ('portion_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomenclatures_portion', to='Packs.pack', verbose_name='Тип упаковки (вложение)')),
                ('templates_box_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomenclatures_box_label', to='LabelTemplates.labeltemplates', verbose_name='Шаблон этикетки короб')),
                ('templates_pack_label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomenclatures_pack_label', to='LabelTemplates.labeltemplates', verbose_name='Шаблон единичной этикетки')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатуры',
            },
        ),
        migrations.CreateModel(
            name='ProductPackLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_links', to='Packs.pack', verbose_name='Упаковка')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_links', to='Nomenclature.nomenclature', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Связь товар-упаковка',
                'verbose_name_plural': 'Связи товар-упаковка',
                'unique_together': {('product', 'pack')},
            },
        ),
    ]
