# Generated by Django 5.2.11 on 2026-03-02 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomenclature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='is_fixed_weight',
            field=models.BooleanField(default=False, verbose_name='Фикс вес'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='max_weight_grams',
            field=models.FloatField(default=0, verbose_name='Макс. допустимый вес (г)'),
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='min_weight_grams',
            field=models.FloatField(default=0, verbose_name='Мин. допустимый вес (г)'),
        ),
    ]
