# Generated by Django 5.2.11 on 2026-03-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomenclature', '0002_nomenclature_is_fixed_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='fixed_weight_grams',
            field=models.FloatField(default=0, verbose_name='Значение фикс. веса (г)'),
        ),
    ]
