# Generated by Django 5.2.15 on 2026-06-22 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabelTemplates', '0002_labeltemplates_created_at_labeltemplates_updated_at'),
        ('Nomenclature', '0003_nomenclature_fixed_weight_grams'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomenclature',
            name='templates_pallet_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nomenclatures_pallet_label', to='LabelTemplates.labeltemplates', verbose_name='Шаблон паллетного листа'),
        ),
    ]
