# Generated by Django 5.2.15 on 2026-06-28 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomenclature', '0004_nomenclature_templates_pallet_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomenclatureFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название папки')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Папка номенклатуры',
                'verbose_name_plural': 'Папки номенклатуры',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='Nomenclature.nomenclaturefolder', verbose_name='Папка'),
        ),
    ]
