server {
    listen 80;
    server_name labelpilot;


    location /static/ {
        alias /code/static/;  # Путь к статическим файлам в контейнере
    }

    location /media/ {
        alias /code/media/;  # Путь к медиафайлам в контейнере
    }

    location / {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}