# Generated by Django 5.2.11 on 2026-02-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название упаковки')),
                ('weight', models.FloatField(default=0, verbose_name='Вес (кг)')),
                ('width', models.IntegerField(default=0, verbose_name='Ширина (мм)')),
                ('height', models.IntegerField(default=0, verbose_name='Высота (мм)')),
                ('depth', models.IntegerField(blank=True, null=True, verbose_name='Глубина (мм)')),
                ('tare', models.IntegerField(blank=True, null=True, verbose_name='Тара (г)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Упаковка',
                'verbose_name_plural': 'Упаковки',
            },
        ),
    ]
