# Generated by Django 5.2.11 on 2026-02-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='height',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='tare',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='width',
        ),
        migrations.AlterField(
            model_name='pack',
            name='weight',
            field=models.FloatField(default=0, verbose_name='Вес (г)'),
        ),
    ]
