# Generated by Django 5.2.11 on 2026-02-07 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LabelTemplates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labeltemplates',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='labeltemplates',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
