# Generated by Django 5.2.10 on 2026-03-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('job_created', 'Задание создано'), ('job_sent', 'Задание отправлено'), ('template_updated', 'Шаблон обновлён'), ('product_added', 'Товар добавлен'), ('report_imported', 'Отчёт импортирован'), ('station_synced', 'Станция синхронизирована'), ('other', 'Прочее')], max_length=30, verbose_name='Действие')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Серверное событие',
                'verbose_name_plural': 'Серверные события',
                'ordering': ['-created_at'],
            },
        ),
    ]
