# Generated by Django 5.2.15 on 2026-10-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_activity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginThrottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64)),
                ('username', models.CharField(blank=True, default='', max_length=150)),
                ('failures', models.PositiveIntegerField(default=0)),
                ('last_failure_at', models.DateTimeField()),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Неверные входы',
                'verbose_name_plural': 'Неверные входы',
                'constraints': [models.UniqueConstraint(fields=('ip', 'username'), name='login_throttle_ip_username')],
            },
        ),
    ]
