# Generated by Django 5.2.11 on 2026-02-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название шаблона')),
                ('structure', models.JSONField(verbose_name='Структура штрихкода')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Шаблон штрихкода',
                'verbose_name_plural': 'Шаблоны штрихкодов',
            },
        ),
    ]
