# Generated by Django 5.2.15 on 2026-06-22 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nomenclature', '0004_nomenclature_templates_pallet_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_number', models.CharField(max_length=100, verbose_name='Номер паллеты')),
                ('shipping_date', models.DateField(blank=True, null=True, verbose_name='Дата отгрузки')),
                ('production_date', models.DateField(blank=True, null=True, verbose_name='Дата производства')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Примечание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Паллета',
                'verbose_name_plural': 'Паллеты',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PalletItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0, verbose_name='Количество')),
                ('batch_number', models.CharField(blank=True, default='', max_length=100, verbose_name='Номер партии')),
                ('weight_netto', models.FloatField(default=0, verbose_name='Вес нетто (кг)')),
                ('weight_brutto', models.FloatField(default=0, verbose_name='Вес брутто (кг)')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallet_items', to='Nomenclature.nomenclature', verbose_name='Номенклатура')),
                ('pallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Pallets.pallet', verbose_name='Паллета')),
            ],
            options={
                'verbose_name': 'Позиция паллеты',
                'verbose_name_plural': 'Позиции паллеты',
                'ordering': ['order', 'id'],
            },
        ),
    ]
