# Generated by Django 5.2.10 on 2026-02-12 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Nomenclature', '0001_initial'),
        ('Packs', '0002_remove_pack_depth_remove_pack_height_and_more'),
        ('label_stations', '0006_add_station_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintedLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_user_name', models.CharField(blank=True, max_length=100, verbose_name='Имя пользователя на станции')),
                ('product_name_snapshot', models.CharField(blank=True, max_length=255, verbose_name='Название продукта (копия)')),
                ('pack_name_snapshot', models.CharField(blank=True, max_length=255, verbose_name='Название упаковки (копия)')),
                ('unique_id', models.CharField(max_length=100, unique=True, verbose_name='Уникальный ID этикетки')),
                ('printed_at', models.DateTimeField(verbose_name='Время печати')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения сервером')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Packs.pack', verbose_name='Упаковка')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nomenclature.nomenclature', verbose_name='Номенклатура')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='label_stations.labelsstations', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Напечатанная этикетка',
                'verbose_name_plural': 'Напечатанные этикетки',
                'ordering': ['-printed_at'],
            },
        ),
        migrations.CreateModel(
            name='StationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Информация'), ('WARNING', 'Предупреждение'), ('ERROR', 'Ошибка')], default='INFO', max_length=20, verbose_name='Уровень')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('timestamp', models.DateTimeField(verbose_name='Время события')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время получения сервером')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='label_stations.labelsstations', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Лог станции',
                'verbose_name_plural': 'Логи станций',
                'ordering': ['-timestamp'],
            },
        ),
    ]
