# Generated by Django 5.2.15 on 2026-06-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductionLogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationlog',
            name='event_uid',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='UID события'),
        ),
    ]
