# Generated by Django 5.2.10 on 2026-06-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductionLogs', '0002_stationlog_event_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='printedlabel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время удаления отвеса'),
        ),
        migrations.AddField(
            model_name='printedlabel',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Отвес удалён'),
        ),
        migrations.AddField(
            model_name='printedlabel',
            name='weight_netto_grams',
            field=models.FloatField(blank=True, null=True, verbose_name='Фактический вес нетто (г)'),
        ),
    ]
