# Generated by Django 5.2.10 on 2026-06-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductionLogs', '0003_printedlabel_deleted_at_printedlabel_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='printedlabel',
            name='barcode',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Штрихкод/код маркировки'),
        ),
        migrations.AddField(
            model_name='printedlabel',
            name='batch',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Партия'),
        ),
        migrations.AddField(
            model_name='printedlabel',
            name='expiration_date',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Срок годности'),
        ),
        migrations.AddField(
            model_name='printedlabel',
            name='production_date',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Дата производства'),
        ),
        migrations.AddField(
            model_name='printedlabel',
            name='weight_brutto_grams',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес брутто (г)'),
        ),
    ]
