# Generated by Django 5.2.15 on 2026-10-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductionLogs', '0004_printedlabel_barcode_printedlabel_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stationlog',
            name='component',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='Подсистема'),
        ),
    ]
