# Generated by Django 5.2.15 on 2026-10-09 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nomenclature', '0005_nomenclaturefolder_nomenclature_folder'),
        ('ProductionLogs', '0005_stationlog_component'),
        ('label_stations', '0012_operator_station_set_null_master_data_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='printedlabel',
            name='box_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Номер короба'),
        ),
        migrations.CreateModel(
            name='PrintedContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('box', 'Короб'), ('pallet', 'Паллета')], db_index=True, max_length=8, verbose_name='Уровень')),
                ('unique_id', models.CharField(max_length=100, unique=True, verbose_name='Уникальный ID')),
                ('number', models.CharField(max_length=64, verbose_name='Номер')),
                ('product_name_snapshot', models.CharField(blank=True, default='', max_length=255, verbose_name='Товар (копия)')),
                ('parent_number', models.CharField(blank=True, default='', max_length=64, verbose_name='Номер паллеты')),
                ('packs_count', models.PositiveIntegerField(default=0, verbose_name='Упаковок')),
                ('boxes_count', models.PositiveIntegerField(default=0, verbose_name='Коробов')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вместимость')),
                ('weight_netto_grams', models.FloatField(blank=True, null=True, verbose_name='Вес нетто (г)')),
                ('weight_brutto_grams', models.FloatField(blank=True, null=True, verbose_name='Вес брутто (г)')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Закрыт')),
                ('opened_at', models.DateTimeField(verbose_name='Открыт')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыт в')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалён')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Удалён в')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Nomenclature.nomenclature', verbose_name='Номенклатура')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='label_stations.labelsstations', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Короб или паллета',
                'verbose_name_plural': 'Короба и паллеты',
                'ordering': ['-opened_at'],
                'indexes': [models.Index(fields=['station', 'level', 'opened_at'], name='ProductionL_station_541f0a_idx')],
            },
        ),
    ]
