# Generated by Django 5.2.15 on 2026-10-09 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductionLogs', '0006_containers_and_box_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_output', models.BooleanField(default=False, verbose_name='Выработка по операторам')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки производственных данных',
            },
        ),
    ]
