# Generated by Django 5.1 on 2024-08-11 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelsstations',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='labelsstations',
            name='station_name',
            field=models.CharField(default='Станция маркировки', max_length=100),
        ),
    ]
