# Generated by Django 5.1 on 2024-09-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_stations', '0002_labelsstations_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelsstations',
            name='stations_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
