# Generated by Django 5.1 on 2024-09-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_stations', '0003_labelsstations_stations_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelsstations',
            old_name='stations_ip',
            new_name='station_ip',
        ),
        migrations.RenameField(
            model_name='labelsstations',
            old_name='stations_uuid',
            new_name='station_uuid',
        ),
        migrations.AddField(
            model_name='labelsstations',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
