# Generated by Django 5.2.11 on 2026-02-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_stations', '0004_rename_stations_ip_labelsstations_station_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelsstations',
            name='station_port',
            field=models.IntegerField(default=5000),
        ),
    ]
