# Generated by Django 5.2.10 on 2026-02-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_stations', '0005_labelsstations_station_port'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelsstations',
            name='station_number',
            field=models.IntegerField(blank=True, help_text='Уникальный двухзначный номер станции (01-99)', null=True, unique=True),
        ),
    ]
