# Generated by Django 5.2.10 on 2026-02-12 15:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_stations', '0006_add_station_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelsstations',
            name='station_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
