# Generated by Django 5.2.10 on 2026-03-24 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_stations', '0007_alter_labelsstations_station_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelsstations',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация'),
        ),
        migrations.AddField(
            model_name='labelsstations',
            name='mode',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Оффлайн'), ('hybrid', 'Гибрид')], default='online', max_length=10, verbose_name='Режим работы'),
        ),
    ]
