# Generated by Django 5.2.15 on 2026-06-24 10:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_stations', '0008_labelsstations_last_sync_at_labelsstations_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('short_code', models.CharField(blank=True, default='', max_length=50, verbose_name='Код/таб. номер')),
                ('pin_hash', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(blank=True, help_text='Пусто = доступен на всех станциях', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operators', to='label_stations.labelsstations', verbose_name='Станция')),
            ],
        ),
    ]
