# Generated by Django 5.2.10 on 2026-10-03 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('label_stations', '0009_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelsstations',
            name='conflict_fingerprint',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='labelsstations',
            name='seat_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labelsstations',
            name='seat_state',
            field=models.CharField(choices=[('active', 'Место выдано'), ('pending', 'Ожидает места'), ('released', 'Место освобождено')], db_index=True, default='active', max_length=16, verbose_name='Лицензионное место'),
        ),
        migrations.AddField(
            model_name='labelsstations',
            name='station_fingerprint',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='SeatEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_uuid', models.UUIDField(blank=True, null=True)),
                ('station_name', models.CharField(blank=True, default='', max_length=100)),
                ('event', models.CharField(db_index=True, max_length=32)),
                ('actor', models.CharField(blank=True, default='', max_length=150)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat_events', to='label_stations.labelsstations')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
