# Generated by Django 5.2.15 on 2026-10-06 17:28

from django.db import migrations, models
from django.db.models import F


def from_last_sync(apps, schema_editor):
    # Best guess for existing stations: their last sync. Without it every product would show
    # as "not on the stations" right after the update.
    Station = apps.get_model('label_stations', 'LabelsStations')
    Station.objects.filter(last_sync_at__isnull=False).update(data_pushed_at=F('last_sync_at'))


class Migration(migrations.Migration):

    dependencies = [
        ('label_stations', '0010_station_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelsstations',
            name='data_pushed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Данные переданы станции'),
        ),
        migrations.RunPython(from_last_sync, migrations.RunPython.noop),
    ]
