# Generated by Django 5.2.15 on 2026-10-05 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=191)),
                ('code', models.CharField(max_length=64)),
                ('severity', models.CharField(choices=[('critical', 'Критично'), ('error', 'Ошибка'), ('warning', 'Предупреждение'), ('info', 'Информация')], max_length=10)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('link_tab', models.CharField(blank=True, default='', max_length=32)),
                ('link_id', models.CharField(blank=True, default='', max_length=64)),
                ('count', models.PositiveIntegerField(default=1)),
                ('first_at', models.DateTimeField()),
                ('last_at', models.DateTimeField(db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['-last_at'],
                'indexes': [models.Index(fields=['key', 'resolved_at'], name='notificatio_key_b64f67_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationSeen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_at', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_seen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
